version: '3.8'
services:
  postgres:
    image: postgres:14.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./packages/api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
  api:
    build: ./packages/api
    environment: 
        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}?ssl=false
    restart:
      unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres

networks:
  my_network:
    driver: bridge
