workflowVersion: 1.0.0
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/panora/panora/panora-open-api-swagger
        overlays:
            - location: registry.speakeasyapi.dev/panora/panora/code-samples-typescript-my-first-target:main
            - location: registry.speakeasyapi.dev/panora/panora/code-samples-python
        output: docs/openapi-with-code-samples.json
targets: {}
