name: Build Docker Images (Selfhosted)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: SELF_HOSTED

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend (Magic Links)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/frontend-snippet/Dockerfile
        push: true
        tags: panoradotdev/frontend-magic-links:latest
        build-args: |
          VITE_BACKEND_DOMAIN=${{ secrets.VITE_BACKEND_DOMAIN }}
          VITE_ML_FRONTEND_URL=${{ secrets.VITE_FRONTEND_DOMAIN }}

    - name: Build and push Frontend (Dashboard)
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/webapp/Dockerfile
        push: true
        tags: panoradotdev/frontend-webapp:latest
        build-args: |
          VITE_BACKEND_DOMAIN=${{ secrets.VITE_BACKEND_DOMAIN }}
          VITE_FRONTEND_DOMAIN=${{ secrets.VITE_FRONTEND_DOMAIN }}

       